# Generated by Django 4.0.5 on 2022-06-25 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=100, verbose_name='страница')),
                ('slug', models.SlugField(verbose_name='слаг')),
            ],
            options={
                'verbose_name': 'карусель',
                'verbose_name_plural': 'карусели',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='заголовок')),
                ('text', models.TextField(blank=True, verbose_name='текст баннера')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='картинка')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='порядок')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='banners.bannercarousel', verbose_name='место баннера')),
            ],
            options={
                'verbose_name': 'баннер',
                'verbose_name_plural': 'баннеры',
                'ordering': ['order'],
            },
        ),
    ]
