# Generated by Django 3.2 on 2022-05-29 20:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, unique=True, verbose_name='адрес')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True, verbose_name='Широта')),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True, verbose_name='Долгота')),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата записи координат')),
            ],
        ),
    ]
