# Generated by Django 3.2 on 2022-05-22 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_auto_20220522_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'позиция заказа', 'verbose_name_plural': 'позиции в заказе'},
        ),
        migrations.AlterField(
            model_name='order',
            name='client_surname',
            field=models.CharField(max_length=50, verbose_name='фамилия клиента'),
        ),
    ]
