# Generated by Django 3.2 on 2022-05-24 05:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_rename_orderitem_orderproductitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproductitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
