# Generated by Django 3.2 on 2022-05-24 06:41

from django.db import migrations


def fill_order_product_items_price_field(apps, schema_editor):
    OrderProductItem = apps.get_model('foodcartapp', 'OrderProductItem')
    Product = apps.get_model('foodcartapp', 'Product')
    order_items = OrderProductItem.objects.all()
    for order_item in order_items.iterator():
        order_item.price = order_item.product.price
        order_item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_orderproductitem_price'),
    ]

    operations = [
        migrations.RunPython(fill_order_product_items_price_field)
    ]

