# Generated by Django 3.2 on 2022-05-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_auto_20220524_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('UNPRCSSED', 'Не обработан'), ('INPROCESS', 'В процессе'), ('COMPLETED', 'Завершен')], db_index=True, default='UNPRCSSED', max_length=9, verbose_name='статус заказа'),
        ),
    ]
