# Generated by Django 3.2 on 2022-05-27 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_order_payment_method'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderProductItem',
            new_name='OrderItem',
        ),
    ]
